require("config.theme")
require("config.options")
require("config.autocmds")
require("config.keymaps")

require("plugins.mini")
require("plugins.oil")
require("plugins.fzf")
require("plugins.treesitter")
require("plugins.lspconfig")
require("plugins.blink")
require("plugins.live-server")
